name: Lint and Test

on: [pull_request]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: "^(feat|fix|docs|style|refactor|test|chore).+"
          error: "Commit messages must begin with a valid commit type."
          excludeDescription: "true"
          excludeTitle: "true"
          checkAllCommitMessages: "true"
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: install npm dependencies
        run: npm ci
      - name: run linters
        run: npm run lint
      - name: run tests
        run: npm run test
